#!/usr/bin/env python3
"""Generate arena snapshot JS constants for skill_arena_demo.html.

Reads all 26 skills' SKILL.md (first 1200 chars) and ARENA.md configs.
Outputs SKILLS_SNAPSHOT and ARENA_CONFIGS as JS const declarations.

Usage:
    python scripts/generate_arena_snapshot.py > /tmp/arena_snapshot.js
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    skills_dir = REPO_ROOT / "skills"
    skills_snapshot: dict[str, dict] = {}
    arena_configs: dict[str, dict] = {}

    # Import ArenaConfig if available
    sys.path.insert(0, str(REPO_ROOT / "skill-organism"))
    try:
        from arena_config import ArenaConfig
        has_arena_config = True
    except ImportError:
        has_arena_config = False

    for skill_dir in sorted(skills_dir.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue

        skill_name = skill_dir.name

        # Read SKILL.md (first 1200 chars)
        skill_text = skill_md.read_text()[:1200]
        skills_snapshot[skill_name] = {
            "name": skill_name,
            "skill_md_preview": skill_text,
            "has_arena": (skill_dir / "ARENA.md").exists(),
            "has_scripts": (skill_dir / "scripts").exists(),
        }

        # Load ARENA.md config
        if has_arena_config:
            try:
                config = ArenaConfig.load(skill_dir)
                arena_configs[skill_name] = config.to_dict()
            except Exception:
                arena_configs[skill_name] = {"skill_name": skill_name, "error": "parse_failed"}
        elif (skill_dir / "ARENA.md").exists():
            arena_configs[skill_name] = {"skill_name": skill_name, "loaded": False}

    # Output as JS constants
    print("// Auto-generated by scripts/generate_arena_snapshot.py")
    print(f"// Generated for {len(skills_snapshot)} skills")
    print()
    print(f"const SKILLS_SNAPSHOT = {json.dumps(skills_snapshot, indent=2)};")
    print()
    print(f"const ARENA_CONFIGS = {json.dumps(arena_configs, indent=2)};")

    # Summary to stderr
    print(f"\n// {len(skills_snapshot)} skills, {len(arena_configs)} arena configs", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
