#!/usr/bin/env python3
"""Generate individual skill documentation pages for GitHub Pages.

Reads each skill's SKILL.md and ARENA.md, then produces a self-contained
HTML page at docs/skills/{skill-name}.html.

Usage:
    python docs/generate_skill_pages.py
"""

from __future__ import annotations

import html
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = REPO_ROOT / "skills"
OUTPUT_DIR = REPO_ROOT / "docs" / "skills"

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{skill_name} — Cortex Research Suite</title>
<style>
:root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #c9d1d9; --muted: #8b949e; --accent: #58a6ff;
    --green: #3fb950;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        background: var(--bg); color: var(--text); line-height: 1.6; }}
.container {{ max-width: 800px; margin: 0 auto; padding: 2rem; }}
h1 {{ color: var(--accent); margin-bottom: 0.5rem; }}
h2 {{ color: var(--green); margin: 1.5rem 0 0.5rem; border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; }}
h3 {{ color: var(--muted); margin: 1rem 0 0.3rem; }}
pre {{ background: var(--surface); padding: 1rem; border-radius: 6px;
       overflow-x: auto; font-size: 0.9rem; margin: 0.5rem 0 1rem; }}
code {{ font-family: 'SF Mono', Monaco, monospace; }}
a {{ color: var(--accent); text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.nav {{ margin-bottom: 2rem; font-size: 0.9rem; }}
.badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 3px;
          font-size: 0.8rem; margin-right: 0.5rem; }}
.badge-arena {{ background: #1f2937; color: var(--green); border: 1px solid var(--green); }}
.badge-trilogy {{ background: #1f2937; color: #d29922; border: 1px solid #d29922; }}
.content {{ white-space: pre-wrap; }}
</style>
</head>
<body>
<div class="container">
<div class="nav"><a href="../index.html">Home</a> / <a href="../index.html#skills">Skills</a> / {skill_name}</div>
<h1>{skill_name}</h1>
{badges}
<h2>SKILL.md</h2>
<pre class="content">{skill_md}</pre>
{arena_section}
<p style="margin-top:2rem;color:var(--muted);font-size:0.8rem;">
Generated by Cortex Research Suite docs pipeline.
<a href="https://github.com/TECHKNOWMAD-LABS/cortex-research-suite">GitHub</a>
</p>
</div>
</body>
</html>
"""


def generate_skill_page(skill_dir: Path) -> str | None:
    """Generate HTML page for a single skill."""
    skill_md_path = skill_dir / "SKILL.md"
    if not skill_md_path.exists():
        return None

    skill_name = skill_dir.name
    skill_md = html.escape(skill_md_path.read_text()[:8000])

    badges = '<span class="badge badge-arena">ARENA.md</span>' if (skill_dir / "ARENA.md").exists() else ""

    arena_section = ""
    arena_path = skill_dir / "ARENA.md"
    if arena_path.exists():
        arena_content = html.escape(arena_path.read_text()[:4000])
        arena_section = f'<h2>ARENA.md</h2>\n<pre class="content">{arena_content}</pre>'

        # Check trilogy fields
        arena_text = arena_path.read_text()
        if "mindspider_feed_enabled: true" in arena_text:
            badges += ' <span class="badge badge-trilogy">MindSpider</span>'
        if "bettafish_engine_type:" in arena_text and "null" not in arena_text.split("bettafish_engine_type:")[1][:20]:
            badges += ' <span class="badge badge-trilogy">BettaFish</span>'
        if "mirofish_simulation_enabled: true" in arena_text:
            badges += ' <span class="badge badge-trilogy">MiroFish</span>'

    return HTML_TEMPLATE.format(
        skill_name=skill_name,
        skill_md=skill_md,
        arena_section=arena_section,
        badges=badges,
    )


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    skills_generated = []
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir() or skill_dir.name.startswith("_"):
            continue
        page = generate_skill_page(skill_dir)
        if page:
            out_path = OUTPUT_DIR / f"{skill_dir.name}.html"
            out_path.write_text(page)
            skills_generated.append(skill_dir.name)

    print(f"Generated {len(skills_generated)} skill pages in {OUTPUT_DIR}")

    # Generate skills index
    index_items = "\n".join(
        f'<li><a href="skills/{s}.html">{s}</a></li>' for s in skills_generated
    )
    skills_index = f"""<!-- Auto-generated skills index fragment -->
<ul>
{index_items}
</ul>
"""
    (OUTPUT_DIR / "_index_fragment.html").write_text(skills_index)
    print(f"Skills index fragment: {OUTPUT_DIR / '_index_fragment.html'}")


if __name__ == "__main__":
    main()
